<a href="https://colab.research.google.com/github/Cqurvozaur/data-science/blob/main/03_Funkcje_statystyczne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Funkcje statystyczne**

In [2]:
import numpy as np

In [3]:
price = np.array([[12.40, 12.80, 11.90, 12.60, 1000],
                  [12.50, 13.00, 11.70, 12.20, 2000],
                  [12.20, 13.40, 12.20, 13.20, 1500]])
print(price)

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.2 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]]


In [4]:
price.sum()

4650.1

In [5]:
price.sum(axis=0) #po kolumnach
price.sum(axis=1) #po wierszach

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [6]:
np.sum(price )

4650.1

In [7]:
np.min(price)

11.7

In [8]:
np.min(price, axis=0)

array([  12.2,   12.8,   11.7,   12.2, 1000. ])

In [9]:
np.max(price)

2000.0

In [10]:
np.max(price, axis=0)

array([  12.5,   13.4,   12.2,   13.2, 2000. ])

In [11]:
np.median(price)

12.6

In [13]:
np.mean(price)

310.0066666666667

In [14]:
np.mean(price, axis=0)

array([  12.36666667,   13.06666667,   11.93333333,   12.66666667,
       1500.        ])

In [15]:
np.std(price)

622.3781502877133

In [16]:
np.var(price)

387354.5619555555