<a href="https://colab.research.google.com/github/Cqurvozaur/data-science/blob/main/Podstawy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

9### **NumPy**


**Spis** **treści**:


*   [Podstawy](https://)
*   Typy danych
*   Tworzenie tablic
*   Podstawowe operacje na tablicach
*   Generowanie liczb pseudolosowych
*   Podstawowe funkcje
*   Indeksowanie, Wycinanie
*   Iteracja po tablicach
*   Zmiana rozmiaru tablic
*   Maski logiczne











Podstawy

In [ ]:
import numpy as np
np.__version__


'1.26.4'

In [ ]:
dir(np)

In [ ]:
help (np.array)

**1D Array**



In [ ]:
x = np.array([1, 3])
x

array([1, 3])

In [ ]:
print(x)

[1 3]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
z = np.array([1.3, 2.4, 3.5, 4.7])
print(z)

[1.3 2.4 3.5 4.7]


In [ ]:
z.dtype

dtype('float64')

**2D Array**

In [ ]:
y = np.array([[1, 2], [3, 4]])
print(y)

[[1 2]
 [3 4]]


In [ ]:
y.ndim

2

In [ ]:
y.size

4

In [ ]:
y.shape

(2, 2)

In [ ]:
n = np.array([[1, 2, 3], [4, 2, 1]])
print(n)

[[1 2 3]
 [4 2 1]]


In [ ]:
n.shape

(2, 3)

**3D Array**

In [ ]:
m = np.array([[[1, 2, 3],
              [4, 5, 6]],

              [[7, 8, 9],
               [10, 11, 12]],

              [[13, 14, 16],
               [17, 18, 19]]]

)
print(m)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 16]
  [17 18 19]]]


In [ ]:
m.ndim

3

In [ ]:
m.shape

(3, 2, 3)

In [ ]:
m.size

18

**Typy danych**

In [ ]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [ ]:
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [ ]:
A = np.array([1, 2, 3], dtype='complex')
A.dtype

dtype('complex128')

In [ ]:
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
A = np.array([1.1, 2.2, 3.3], dtype='int')
A.dtype

dtype('int64')

In [ ]:
A

array([1, 2, 3])

In [ ]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [ ]:
A = np.array([24, 120, 230], dtype=np.int8)
A.dtype

<ipython-input-50-27ab11b0e872>:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 230 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  A = np.array([24, 120, 230], dtype=np.int8)


dtype('int8')

In [ ]:
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

dtype('uint8')

**Tworzenie Tablic**

In [ ]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape=(5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.ones(shape=(5, 5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [ ]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [ ]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((-1,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

**Podstawowe operacje na tablicach**

In [ ]:
A = np.array([3, 1, 2, 4])
B = np.array([3, -1, 4, 2 ])
print(A)
print(B)


[3 1 2 4]
[ 3 -1  4  2]


In [ ]:
A + B

array([6, 0, 6, 6])

In [ ]:
A - B

array([ 0,  2, -2,  2])

In [ ]:
A * B

array([ 9, -1,  8,  8])

In [ ]:
A / B

array([ 1. , -1. ,  0.5,  2. ])

In [ ]:
A * 3

array([ 9,  3,  6, 12])

In [ ]:
X = np.array([[1, 2], [2, 3]] )
Y = np.array([[5, 6], [7, 8]])

In [ ]:
print(X)
print(Y)

[[1 2]
 [2 3]]
[[5 6]
 [7 8]]


In [ ]:
np.dot(X, Y)

array([[19, 22],
       [31, 36]])

In [ ]:
Y.dot(X)

array([[17, 28],
       [23, 38]])

In [ ]:
X.dot(Y)

array([[19, 22],
       [31, 36]])

In [ ]:
X @ Y

array([[19, 22],
       [31, 36]])

**Liczby pseudolosowe**

In [ ]:
np.random.seed(0)

In [ ]:
np.random.randn()

1.764052345967664

In [ ]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [ ]:
A = np.random.randn(10, 4)

In [ ]:
np.random.rand(10, 2)

array([[0.19658236, 0.36872517],
       [0.82099323, 0.09710128],
       [0.83794491, 0.09609841],
       [0.97645947, 0.4686512 ],
       [0.97676109, 0.60484552],
       [0.73926358, 0.03918779],
       [0.28280696, 0.12019656],
       [0.2961402 , 0.11872772],
       [0.31798318, 0.41426299],
       [0.0641475 , 0.69247212]])

In [ ]:
np.random.randint(10)

6

In [ ]:
np.random.randint(low=10, high=101)

89

In [ ]:
np.random.randint(low = 10, high = 100, size = 10)

array([21, 48, 11, 54, 98, 34, 77, 92, 13, 86])

In [ ]:
np.random.choice([1, 2, 3, 4 ,5])

4

In [ ]:
np.random.choice(['python', 'java', 'sql'])

'sql'

In [ ]:
data = np.arange(10)
data


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(data)
data

array([1, 6, 2, 8, 3, 4, 5, 7, 0, 9])

**Podstawowe funkcje**

In [ ]:
import numpy as np


In [ ]:
np.exp(1)

2.718281828459045

In [ ]:
np.exp(10)

22026.465794806718

In [ ]:
np.sqrt(9)

3.0

In [ ]:
np.all([2, 3, 1])

True

In [ ]:
np.any([1, 2, 3])

True

In [ ]:
np.any([0, 0, 0])

False

In [ ]:
bool(1.3)

True

In [ ]:
A = np.random.rand(5)
A


array([0.27142485, 0.66555631, 0.59315984, 0.12976611, 0.80553126])

In [ ]:
np.argmax(A)

4

In [ ]:
A[np.argmax(A)]

0.8055312601859856

In [ ]:
np.argmin(A)

3

In [ ]:
A[np.argmin(A)]

0.12976611289545958

In [ ]:
np.argsort(A)

array([3, 0, 2, 1, 4])

In [ ]:
np.max(A)

0.8055312601859856

In [ ]:
np.min(A)

0.12976611289545958

In [ ]:
np.median(A)

0.5931598409117389

In [ ]:
np.std(A)

0.2523956521784804

**Indeksowanie, wycinanie**


In [ ]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
#A[idx], A[start:stop], A[:stop], A[start:]

In [ ]:
A[2]

2

In [ ]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [ ]:
A[-1]

19

In [ ]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A[1]

array([5, 6, 7, 8, 9])

In [ ]:
A[:,3]

array([ 3,  8, 13, 18])

In [ ]:
A[1, 1]

6

In [ ]:
A[1, 2]

7

In [ ]:
A[1:4, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [ ]:
A[1, 2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

**Iteracja po tablicach**

In [ ]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [ ]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [ ]:
for row in A:
  print(row[1:4])

[1 2 3]
[ 6 14  8]
[11 12 13]
[16 17 18]


In [ ]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


**Zmiana rozmiaru tablic**

In [ ]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

**Maski logiczne**

In [ ]:
A = np.arange(start = -10, stop = 10, step = 0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [ ]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
A[A > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [ ]:
np.bitwise_or(A > 5, A < -5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])